package com.smokeythebandicoot.zencloche;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import org.apache.logging.log4j.Logger;

@Mod(
        modid = ZenCloche.MODID,
        version = ZenCloche.MODVERSION,
        name = ZenCloche.MODNAME,
        acceptedMinecraftVersions = "[1.12.2]",
        useMetadata = true)
public class ZenCloche {

    public static final String MODID = "zencloche";
    public static final String MODNAME = "Zen Cloche";
    public static final String MODVERSION = "1.0";
    public static final String MODDESCRIPTION = "A mod to add compatibility between modded crops and Immersive Engineering Garden Cloche.";
    public static final String MODAUTHOR = "SmokeyTheBandicoot";
    public static final String MODCREDITS = "";
    public static final String MODURL = "";
    public static final String MODLOGO = "assets/zencloche/textures/logo.png";

    public static Logger logger;
    @Instance(value = MODID)
    public static ZenCloche instance;

    @EventHandler
    public void onPreInit(FMLPreInitializationEvent event) {
        logger = event.getModLog();

        // Set mod info
        event.getModMetadata().autogenerated = false; // stops it from complaining about missing mcmod.info
        event.getModMetadata().name = MODID;
        event.getModMetadata().credits = MODCREDITS;
        event.getModMetadata().authorList.clear();
        event.getModMetadata().authorList.add(MODAUTHOR);
        event.getModMetadata().description = MODDESCRIPTION;
        event.getModMetadata().url = MODURL;
        event.getModMetadata().logoFile = MODLOGO;
    }
}
